### ISSUE TITLE
Simple way to fix ImportError (PyQt5 and PySide conflict)?

### ISSUE THREAD

**Issue by htrej** [fireeye/flare-ida#39]
![image](https://cloud.githubusercontent.com/assets/16462860/19968784/fe202868-a1a3-11e6-8bf3-334f832c1f9d.png)

Above image probably illustrates error better than I can explain.

**Comment by williballenthin** [comment]
what version of IDA are you using to run these plugins?

**Comment by htrej** [comment]
IDA Pro version 6.8.

**Comment by williballenthin** [comment]
around May, 2016 we updated many of the plugins to use PyQt5, since this is what IDA 6.9 uses. you can try going back to a commit in April and see if that works for you. the list of commits is here: https://github.com/fireeye/flare-ida/commits/master Maybe try the commit with sha: 21ad64137e2af97d03ea5e1027c8b3eadcfe3d30

**Comment by htrej** [comment]
Yep, that worked. Hopefully I wont miss out on too much for later releases
