### ISSUE TITLE
Parse_decl2 too many arguments error

### ISSUE THREAD

**Issue by keithjjones** [fireeye/flare-ida#43]
This line fails because the current parse_decl2 has one less argument now:

https://github.com/fireeye/flare-ida/blob/master/python/flare/apply_callee_type.py#L67

Taking out "blah" still throws an error, and I'm not sure why.

**Comment by jhsmith** [comment]
Thanks for reporting the error. I think IDAPython's SWIG usage may have changed the behavior of calling parse_decl2 since this was originally written. I think I'm now using parse_decl2 correctly. Please try the latest in master.

**Comment by keithjjones** [comment]
@jhsmith Well, it didn't crash which is good.  But it didn't change my call at all:

![image](https://cloud.githubusercontent.com/assets/5360855/24051458/7add1a78-0b08-11e7-9ebd-a76f8c47660b.png)

What are the manual steps to apply the same type of typing this script does?  I'd like to see if I can do it manually to see if it is even possible.  I can't find, or I'm not aware of, anything in the GUI that will let you do the same thing.

**Comment by keithjjones** [comment]
I should note - those commends in there are ones I wrote.

**Comment by jhsmith** [comment]
Did IDA pop up an error box about the type declaration being invalid? What function prototype did you try to apply at the address? Can you paste it here in a message?

**Comment by keithjjones** [comment]
No popup errors.  This is what I defined it as:

```
int LdrLoadDll (
  PWCHAR               PathToFile,
  ULONG                Flags,
  PUNICODE_STRING      ModuleFileName,
  PHANDLE             ModuleHandle );
```
Are there manual steps I can try to see if it is even possible to add this?  I can't find similar functionality through the GUI.

**Comment by jhsmith** [comment]
It seems to work for me. I tried it out on a random 4-argument function in an idb. See here pictures attached. Try deleting your comments on the lines with the pushes, and make sure the cursor is on the line with the call, and try running it again.

"Are there manual steps I can try to see if it is even possible to add this?" -> that's why I wrote this plugin, because as far as I can tell you can't do this via the GUI, only from scripting/plugins.

![a](https://cloud.githubusercontent.com/assets/974519/24058421/67662a48-0b21-11e7-89bb-a76737467a94.png)
![b](https://cloud.githubusercontent.com/assets/974519/24058422/6a6ba4e8-0b21-11e7-994d-18d3b7c914b8.png)
![c](https://cloud.githubusercontent.com/assets/974519/24058427/6c7506b2-0b21-11e7-96ad-fd1aea483066.png)

**Comment by keithjjones** [comment]
Spot on!  Getting rid of the comments was the solution!

![image](https://cloud.githubusercontent.com/assets/5360855/24064515/4d8e444c-0b3b-11e7-8bd2-6a9088a27b74.png)

I thought maybe I was missing a GUI command somewhere.  I'm glad to know I'm not the only one that couldn't figure it out.  Very nice plugin!  Very useful!  Thank you!
