### ISSUE TITLE
idb2pat, is it working for MIPS ?

### ISSUE THREAD

**Issue by dummys** [fireeye/flare-ida#9]
Hello, I'm trying to use your script on a MIPSL binary and I'm getting this error.

ERROR:Python int too large to convert to C long

**Comment by williballenthin** [comment]
is there any other stack trace information visible that you can share with me? that will help me find the function with the overflow, and hopefully get it working for you.

if there's any chance you can share the binary then that would certainly help, but i understand it may be sensitive. so if you cannot, we can continue to discuss and traige the bug here.

**Comment by dummys** [comment]
Yeah the binary is not an option, sorry.
I'm at home now, I share with you the trace tomorrow.
Thanks

**Comment by dummys** [comment]
INFO:idb2pat:make_func_sigs:[ 0 / 9215 ] _start 0x80001000L
ERROR:idb2pat:make_func_sigs:Python int too large to convert to C long
Traceback (most recent call last):
  File "G:/tools/hexrays/ida/ida_plugins_scripts/flare_repo/python/flare/idb2pat.py", line 360, in make_func_sigs
    sigs.append(make_func_sig(config, f))
  File "G:/tools/hexrays/ida/ida_plugins_scripts/flare_repo/python/flare/idb2pat.py", line 193, in make_func_sig
    ref_loc = find_ref_loc(config, ea, ref)
  File "G:/tools/hexrays/ida/ida_plugins_scripts/flare_repo/python/flare/idb2pat.py", line 143, in find_ref_loc
    for i in xrange(ea, get_item_end(ea) - config.pointer_size):
OverflowError: Python int too large to convert to C long
ERROR:idb2pat:make_func_sigs:Failed to create signature for function at 0x80001000L (_start)
INFO:idb2pat:make_func_sigs:[ 1 / 9215 ] _invalidate_cache 0x8000129cL
ERROR:idb2pat:make_func_sigs:Python int too large to convert to C long

And there is ton like this.

**Comment by williballenthin** [comment]
thanks for the traceback --- that leads me to believe the issue is in the `xrange` function, which has an odd limitation of having the platform's MAXINT has the upper bound.

would you try the script found here: https://raw.githubusercontent.com/williballenthin/flare-ida/c5259ffc2abaf9e757d0d53352ee2d3b99c5b60e/python/flare/idb2pat.py

this replaces calls to `xrange` with `zrange`, a function that shouldn't have this limitation.

**Comment by dummys** [comment]
Seems good for this issue, but another happend.

Here the log.

ERROR:idb2pat:make_func_sigs:list assignment index out of range
Traceback (most recent call last):
  File "G:/tools/hexrays/ida/ida_plugins_scripts/flare_repo/python/flare/idb2pat.py", line 379, in make_func_sigs
    sigs.append(make_func_sig(config, f))
  File "G:/tools/hexrays/ida/ida_plugins_scripts/flare_repo/python/flare/idb2pat.py", line 264, in make_func_sig
    crc_data[i - 32] = get_byte(func.startEA + i)
IndexError: list assignment index out of range
